import type { MaintenanceBlock, ShadowBlock } from '@/types'
import { TODAY_ISO } from '@/data/network'

/* ============================================================
 * Seed blocks for TODAY — the "current tactical plan".
 * ============================================================ */

let seq = 1

const mk = (
  department: MaintenanceBlock['department'],
  codeNum: number,
  section: string,
  fromKm: number,
  toKm: number,
  startMin: number,
  endMin: number,
  tasks: string[],
  notes: string,
  status: MaintenanceBlock['status'] = 'PROPOSED',
  source: MaintenanceBlock['source'] = 'AI',
  taskCount?: number,
): MaintenanceBlock => ({
  id: `BLK-${seq++}`,
  code: `BLK-${String(codeNum).padStart(2, '0')}`,
  department,
  departmentLabel:
    department === 'TMS' ? 'TRACK' : department === 'SMMS' ? 'S&T' : 'TRACTION',
  section,
  fromKm,
  toKm,
  startMin,
  endMin,
  durationMin: endMin - startMin,
  date: TODAY_ISO,
  status,
  source,
  taskCount: taskCount ?? tasks.length,
  trainDelayImpactMin: Math.round((endMin - startMin) / 18),
  utilizationPct: Math.round(55 + Math.random() * 30),
  tasks,
  notes,
})

export const B: MaintenanceBlock[] = [
  mk('TMS', 1, 'DWN-MTJ', 22, 34, 0, 120, ['T-1022', 'T-1034'], 'GP 26t track machine — deep screening', 'ACTIVE', 'AI', 2),
  mk('SMMS', 2, 'MTJ-AGRA', 110, 118, 60, 165, ['S-1100'], 'Point machine overhaul at GTR cabin', 'PROPOSED', 'AI', 2),
  mk('TDMS', 3, 'MTJ-AGRA', 104, 112, 60, 150, ['O-1004'], 'OHE stagger correction near NGL', 'ACTIVE', 'ROUTINE', 1),
  mk('TMS', 4, 'AGRA-GWL', 204, 214, 60, 180, ['T-1055'], 'Ballast replenishment — BND crossover', 'PROPOSED', 'ROUTINE', 3),
  mk('SMMS', 5, 'AGRA-GWL', 196, 202, 300, 420, ['S-1188'], 'IB signal relay renew between AGRA-GWL', 'PROPOSED', 'AI', 1),
  mk('TDMS', 6, 'GWL-JHS', 318, 326, 330, 450, ['O-1030'], 'Overlap span adjustment at MOR cabin', 'APPROVED', 'AI', 2),
  mk('TMS', 7, 'JHS-BPL', 456, 468, 0, 150, ['T-1180', 'T-1201', 'T-1219'], 'GRS office — tamping cycle GKP', 'APPROVED', 'AI', 3),
  mk('TMS', 8, 'JHS-BPL', 640, 652, 900, 1080, ['T-1233'], 'LWR destressing near JRO', 'PROPOSED', 'MANUAL', 1),
  mk('SMMS', 9, 'JHS-BPL', 560, 566, 360, 480, ['S-1244'], 'Track circuit renewal at BND', 'PROPOSED', 'AI', 1),
  mk('TDMS', 10, 'BPL-NGP', 730, 740, 0, 120, ['O-1150', 'O-1152'], 'Contact wire wear check + patrolling', 'ACTIVE', 'AI', 2),
  mk('TMS', 11, 'BSL-UMN', 1500, 1512, 870, 1020, ['T-1300'], 'Kipling excavation — BSL Division', 'PROPOSED', 'ROUTINE', 2),
  mk('SMMS', 12, 'DWN-MTJ', 40, 46, 0, 90, ['S-1010'], 'Track circuit bonding renew at KM 44', 'ACTIVE', 'AI', 1),
  mk('TMS', 13, 'BSL-UMN', 1560, 1572, 1050, 1200, ['T-1401', 'T-1410'], 'Deep screening — 3rd day of cycle', 'PROPOSED', 'MANUAL', 2),
  mk('TDMS', 14, 'NGP-BSL', 900, 910, 420, 540, ['O-1220'], 'Neutral section insulator renew', 'PROPOSED', 'EMERGENCY', 1),
  mk('TMS', 15, 'AGRA-GWL', 240, 250, 240, 390, ['T-1100'], 'Rail fracture site — SPL inspection', 'PROPOSED', 'EMERGENCY', 1),
  mk('SMMS', 16, 'GWL-JHS', 330, 336, 1140, 1260, ['S-1300'], 'Cable joint resleeving — fibre optic', 'PROPOSED', 'AI', 1),
]

export const SHADOW_FIXTURES: ShadowBlock[] = [
  {
    id: 'SH-1',
    primaryBlockId: 'BLK-4',
    primaryDepartment: 'TMS',
    department: 'SMMS',
    section: 'AGRA-GWL',
    distanceKm: 1.2,
    startMin: 60,
    endMin: 180,
    durationMin: 120,
    savedTimeMin: 110,
    utilizationGainPct: 18,
    taskIds: ['S-1188'],
    status: 'OPPORTUNITY',
    safetyCleared: true,
  },
  {
    id: 'SH-2',
    primaryBlockId: 'BLK-4',
    primaryDepartment: 'TMS',
    department: 'TDMS',
    section: 'AGRA-GWL',
    distanceKm: 0.8,
    startMin: 60,
    endMin: 180,
    durationMin: 120,
    savedTimeMin: 115,
    utilizationGainPct: 21,
    taskIds: ['O-1030'],
    status: 'OPPORTUNITY',
    safetyCleared: true,
  },
  {
    id: 'SH-3',
    primaryBlockId: 'BLK-1',
    primaryDepartment: 'TMS',
    department: 'SMMS',
    section: 'DWN-MTJ',
    distanceKm: 2.4,
    startMin: 0,
    endMin: 120,
    durationMin: 120,
    savedTimeMin: 60,
    utilizationGainPct: 12,
    taskIds: ['S-1010'],
    status: 'OPPORTUNITY',
    safetyCleared: false,
  },
  {
    id: 'SH-4',
    primaryBlockId: 'BLK-7',
    primaryDepartment: 'TMS',
    department: 'SMMS',
    section: 'JHS-BPL',
    distanceKm: 3.1,
    startMin: 0,
    endMin: 150,
    durationMin: 150,
    savedTimeMin: 80,
    utilizationGainPct: 15,
    taskIds: ['S-1244'],
    status: 'OPPORTUNITY',
    safetyCleared: true,
  },
]